apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-mmks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-mmks
    app.kubernetes.io/part-of: test-app-isvc
  name: test-component-mmks
  namespace: build-e2e-hacbs-uofo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-mmks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-mmks
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:0da8e88519414eaabaa616ef152e3b2a
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
